### ISSUE TITLE
有一處格式或許不一致　

### ISSUE THREAD

**Issue by frankang** [mahawu/BM_u8#2]
> T55n2145_p0001b18P##集三藏緣記第一
> T55n2145_p0001b19P##十誦律五百羅漢出三藏記第二
> T55n2145_p0001b20P##菩薩處胎經出八藏記第三
> T55n2145_p0001b21P##胡漢譯經文字音義同異記第四
> T55n2145_p0001b22P##前後出經異記第五

> T85n2776_p0439c06P#F釋肇序略分四
> T85n2776_p0439c07P#F　初通本迹分二

上面用P##表示，下面用P#F表示，是否存在不一致？

**Comment by mahawu** [comment]
那是早期的BM標記方式，F應該是「分」。比較後期的標記都當做標題，改用Q。

maha

frankang <notifications@github.com> 於 2018年2月2日 上午8:28 寫道：
